# Cloudinary Credentials Configuration
# Place your actual Cloudinary credentials below
# This file should be added to .gitignore to prevent committing sensitive information

cloud_name: "dzqqj6xst"
upload_preset: "academia_hub"
api_key: "996823788687435" # Optional for client-side uploads with upload_preset
api_secret: "VmlKt9Y0FIqmqbHwhhCvczKBdEw" # Optional for client-side uploads with upload_preset

# Replace the above placeholders with your actual Cloudinary credentials
# You can find these in your Cloudinary dashboard at https://cloudinary.com/console 