name: academia_hub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.6.7
  csv: ^6.0.0
  shared_preferences: ^2.5.3
  file_picker: ^10.1.2
  cloudinary_public: ^0.23.1
  yaml: ^3.1.0
  path: ^1.8.2
  url_launcher: ^6.2.3
  dio: ^5.8.0+1
  http: ^1.2.1
  http_parser: ^4.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  crypto: ^3.0.6
  open_file: ^3.3.2
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/screen2.png
    - assets/screen3.png
    - assets/screen4.png
    - assets/google.png
    - assets/data/
    - assets/config/
    - assets/pdf.png
    - assets/doc.png
    - assets/ppt.png
